export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_NOTE_TO_CATEGORY = "ADD_NOTE_TO_CATEGORY";
export const SET_SELECTED_CATEGORY_ID = "SET_SELECTED_CATEGORY_ID";
export const SEARCH_NOTES = "SEARCH_NOTES";
export const EDIT_NOTE = "EDIT_NOTE";
export const DELETE_NOTE = "DELETE_NOTE";
